FROM tiangolo/uvicorn-gunicorn:python3.9-slim

RUN apt-get update && apt-get install -y netcat

WORKDIR /opt


COPY ./requirements.txt /opt/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /opt/requirements.txt


COPY . .